server {
    listen 80;
    server_name test.mgt.com pma.mgt.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name test.mgt.com;

    ssl_certificate /etc/nginx/certs/test.mgt.com.crt;
    ssl_certificate_key /etc/nginx/certs/test.mgt.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://varnish:6081;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
    }
}

server {
    listen 443 ssl http2;
    server_name pma.mgt.com;

    ssl_certificate /etc/nginx/certs/test.mgt.com.crt;
    ssl_certificate_key /etc/nginx/certs/test.mgt.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://nginx-backend:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
    }
}
